# Configuração da Porta da Aplicação
server.port=8080

# Logging
logging.level.root=INFO
logging.level.com.Jose.sistemaingressos=DEBUG

# Configuração do Jackson para JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.indent-output=true
